---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: development
    service: ${BACKEND_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: "#!/bin/bash\ninstall_node() {\nNODE_VERSION=v8.9.4\nINSTALL_NAME=node-v8.9.4-linux-x64\n\
      if [ ! -e $INSTALL_NAME.tar.gz ]; then\nwget \"http://nodejs.org/dist/$NODE_VERSION/$INSTALL_NAME.tar.gz\"\
      \necho 'Untarring'\ntar xf $INSTALL_NAME.tar.gz\nfi      \nNODE_8_INSTALL_DIR=`pwd`/$INSTALL_NAME/bin\n\
      PATH=$NODE_8_INSTALL_DIR:$PATH\n}\ninstall_node\n# Verifying that Node version\
      \ is correct\nnode -v\nnpm install -g yarn\nyarn install\nyarn build"
- name: Staging Environment
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: HTTPS
    value: 'TRUE'
    type: text
  - name: CORS_ORIGIN
    value: ${CORS_ORIGIN}
    type: text
  jobs:
  - name: Deploy to Staging
    type: deployer
    deploy_permission: TOOLCHAIN_MEMBERS
    deploy_type: cf
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_TEST_APP_NAME}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"
- name: Production Environment
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: HTTPS
    value: 'TRUE'
    type: text
  - name: CORS_ORIGIN
    value: ${CORS_ORIGIN}
    type: text
  jobs:
  - name: Deploy to Production
    type: deployer
    deploy_permission: TOOLCHAIN_MEMBERS
    deploy_type: cf
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_APP_NAME}
    script: |-
      #!/bin/bash
      cf push "${CF_APP}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish