---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: development
    service: ${BACKEND_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: "#!/bin/bash\n# Specify and install Node version\nnode_version=v8.9.4\n\
      install_name=node-v8.9.4-linux-x64\nif [ ! -e $install_name.tar.gz ]; then\n\
      wget \"http://nodejs.org/dist/$node_version/$install_name.tar.gz\"\necho 'Untarring'\n\
      tar xf $install_name.tar.gz\nfi\nNODE_8_INSTALL_DIR=`pwd`/$install_name/bin\n\
      PATH=$NODE_8_INSTALL_DIR:$PATH\n# Verifying that Node version is correct\nnode\
      \ -v \nnpm install -g yarn\nyarn install\nyarn build"
- name: Staging Environment
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: HTTPS
    value: 'TRUE'
    type: text
  - name: CORS_ORIGIN
    value: ${CORS_ORIGIN}
    type: text
  jobs:
  - name: Deploy to Staging
    type: deployer
    deploy_permission: TOOLCHAIN_MEMBERS
    deploy_type: cf
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_TEST_APP_NAME}
    script: |
      #!/bin/bash
      cf push "${CF_APP}"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish