---
stages:
- name: Build Stage
  inputs:
  - type: git
    branch: development
    service: ${BACKEND_REPO}
    dir_name: null
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: npm
    script: "bjeff"
- name: Staging Environment
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: CUSTOM_APP_NAME 
    value: ${CUSTOM_APP_NAME}
    type: text
  - name: HTTPS
    value: 'TRUE'
    type: text
  - name: CORS_ORIGIN
    value: ${CORS_ORIGIN}
    type: text
  jobs:
  - name: Deploy to Staging
    type: deployer
    deploy_permission: TOOLCHAIN_MEMBERS
    deploy_type: cf
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_TEST_APP_NAME}
    script: "bjeff"
- name: Production Environment
  inputs:
  - type: job
    stage: Build Stage
    job: Build
    dir_name: null
  triggers:
  - type: stage
  properties:
  - name: CUSTOM_APP_NAME 
    value: ${CUSTOM_APP_NAME}
    type: text
  - name: HTTPS
    value: 'TRUE'
    type: text
  - name: CORS_ORIGIN
    value: ${CORS_ORIGIN}
    type: text
  jobs:
  - name: Deploy to Production
    type: deployer
    deploy_permission: TOOLCHAIN_MEMBERS
    deploy_type: cf
    target:
      region_id: ${BE_PROD_REGION_ID}
      organization: ${BE_PROD_ORG_NAME}
      space: ${BE_PROD_SPACE_NAME}
      application: ${BE_CF_APP_NAME}
    script: "bjeff"
hooks:
- enabled: true
  label: null
  ssl_enabled: false
  url: https://devops-api.ng.bluemix.net/v1/messaging/webhook/publish
